all:
	#mipsel-linux-gcc main.cpp sha1.cpp -o cfw_1.2 -lstdc++ -lSDL_image -lSDL -lSDL_ttf -I/home/steward/Github/gh_retrogame_toolchain/mipsel-linux-gcc/usr/mipsel-buildroot-linux-uclibc/sysroot/usr/include/SDL
	gcc main.cpp sha1.cpp -g -o cfw_1.2 -lstdc++ -lSDL_image -lSDL -lSDL_ttf -I/usr/include/SDL
clean:
	rm -rf cfw_1.2
