main: main.cpp
	mipsel-linux-gcc main.cpp -o hw_scale -lSDL_image -lSDL -I/home/steward/Github/gh_retrogame_toolchain/mipsel-linux-gcc/usr/mipsel-buildroot-linux-uclibc/sysroot/usr/include/SDL
	#gcc main.cpp -o hw_scale -lSDL_image -lSDL -I/usr/include/SDL
clean:
	rm -rf hw_scale
